# coding: utf-8

from __future__ import absolute_import
from backend_server.models.base_model_ import Model
from backend_server import util


class Group(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, group_id: int=None, name: str=None):  # noqa: E501
        """Group - a model defined in Swagger

        :param group_id: The group_id of this Group.  # noqa: E501
        :type group_id: str
        :param name: The name of this Group.  # noqa: E501
        :type name: str
        """
        self.swagger_types = {
            'id': int,
            'name': str,
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
        }

        self._id = group_id
        self._name = name

    @classmethod
    def from_dict(cls, dikt) -> 'Group':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Group of this Group.  # noqa: E501
        :rtype: Group
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Group.


        :return: The id of this Group.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, group_id: int):
        """Sets the id of this Group.


        :param group_id: The id of this Group.
        :type group_id: int
        """

        self._id = group_id

    @property
    def name(self) -> str:
        """Gets the name of this Group.


        :return: The name of this Group.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Group.


        :param name: The name of this Group.
        :type name: str
        """

        self._name = name
