# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from backend_server.models.base_model_ import Model
from backend_server import util


class User(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, user_id: int=None, username: str=None, name: str=None, group_id: int=None, password: str=None):  # noqa: E501
        """User - a model defined in Swagger

        :param username: The username of this User.  # noqa: E501
        :type username: str
        :param name: The name of this User.  # noqa: E501
        :type name: str
        :param group_id: The group_id of this User.  # noqa: E501
        :type group_id: int
        :param password: The password for this User
        :type: password: str
        """
        self.swagger_types = {
            'id': int,
            'username': str,
            'name': str,
            'group_id': int,
            'password': str,
        }

        self.attribute_map = {
            'id': 'id',
            'username': 'username',
            'name': 'name',
            'group_id': 'group_id',
            'password': 'password'
        }

        self._id = user_id
        self._username = username
        self._name = name
        self._group_id = group_id
        self._password = password

    @classmethod
    def from_dict(cls, dikt) -> 'User':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The User of this User.  # noqa: E501
        :rtype: User
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this User.


        :return: The id of this User.
        :rtype: str
        """
        return self._username

    @id.setter
    def id(self, user_id: int):
        """Sets the id of this User.


        :param user_id: The id of this User.
        :type user_id: int
        """

        self._id = user_id

    @property
    def username(self) -> str:
        """Gets the username of this User.


        :return: The username of this User.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username: str):
        """Sets the username of this User.


        :param username: The username of this User.
        :type username: str
        """

        self._username = username

    @property
    def name(self) -> str:
        """Gets the name of this User.


        :return: The name of this User.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this User.


        :param name: The name of this User.
        :type name: str
        """

        self._name = name

    @property
    def group_id(self) -> int:
        """Gets the group_id of this User.


        :return: The group_id of this User.
        :rtype: int
        """
        return self._group_id

    @group_id.setter
    def group_id(self, group_id: int):
        """Sets the group_id of this User.


        :param group_id: The group_id of this User.
        :type group_id: int
        """

        self._group_id = group_id

    @property
    def password(self) -> str:
        """Gets the password of this User.


        :return: The password of this User.
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password: str):
        """Sets the group_id of this User.


        :param password: The password of this User.
        :type password: str
        """

        self._password = password
